### ISSUE TITLE
Document default lookup pattern and make it configurable

### ISSUE THREAD

**Issue by ssbarnea** [shyim/junit-report-annotations-action#4]
Apparently the file lookup pattern is neither documented or configurable, I had to see it in an error.

Actions do allow arguments, so it should not be so hard to add this feature.

**Comment by shyim** [comment]
You mean this?
https://github.com/shyim/junit-report-annotations-action/blob/master/action.yml#L13

**Comment by shyim** [comment]
I have updated the README :)
